#!/bin/env python

import re
import os
import argparse

p = argparse.ArgumentParser()
p.add_argument('old')
p.add_argument('new')
p.add_argument('-r', help='recursive', action='store_true')
p.add_argument('--dry', help='don\'t actually rename, only show info', action='store_true')

args = p.parse_args()

reg = re.compile(args.old)

for r, d, f in os.walk('.'):
    for n in f:
        if reg.search(n):
            new_name = reg.sub(args.new, n)

            print(f'{n} ~> {new_name}')

            if not args.dry:
                os.rename(
                    os.path.join(r, n), 
                    os.path.join(r, new_name)
                )

    if not args.r: break